// This file is generated by icon spritesheet generator

export const iconNames = [
  "Moon",
  "Minus",
  "Monitor",
  "Cross",
  "Spinner",
  "Sun",
  "RailwayWordmark",
  "Check",
  "ThreeDotsHorizontal",
  "ChevronRight",
  "ChevronUp",
  "ChevronDown",
  "Circle",
] as const;

export type IconName = (typeof iconNames)[number];
