/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCompareLatencyPublicRouteImport } from './routes/api/compare-latency-public'
import { Route as ApiCompareLatencyRouteImport } from './routes/api/compare-latency'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompareLatencyPublicRoute = ApiCompareLatencyPublicRouteImport.update({
  id: '/api/compare-latency-public',
  path: '/api/compare-latency-public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompareLatencyRoute = ApiCompareLatencyRouteImport.update({
  id: '/api/compare-latency',
  path: '/api/compare-latency',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/compare-latency': typeof ApiCompareLatencyRoute
  '/api/compare-latency-public': typeof ApiCompareLatencyPublicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/compare-latency': typeof ApiCompareLatencyRoute
  '/api/compare-latency-public': typeof ApiCompareLatencyPublicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/compare-latency': typeof ApiCompareLatencyRoute
  '/api/compare-latency-public': typeof ApiCompareLatencyPublicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/compare-latency' | '/api/compare-latency-public'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/compare-latency' | '/api/compare-latency-public'
  id: '__root__' | '/' | '/api/compare-latency' | '/api/compare-latency-public'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCompareLatencyRoute: typeof ApiCompareLatencyRoute
  ApiCompareLatencyPublicRoute: typeof ApiCompareLatencyPublicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compare-latency-public': {
      id: '/api/compare-latency-public'
      path: '/api/compare-latency-public'
      fullPath: '/api/compare-latency-public'
      preLoaderRoute: typeof ApiCompareLatencyPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compare-latency': {
      id: '/api/compare-latency'
      path: '/api/compare-latency'
      fullPath: '/api/compare-latency'
      preLoaderRoute: typeof ApiCompareLatencyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCompareLatencyRoute: ApiCompareLatencyRoute,
  ApiCompareLatencyPublicRoute: ApiCompareLatencyPublicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
